# Generated by Django 5.1.7 on 2025-03-07 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=10)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('points_per_game', models.FloatField(default=0)),
                ('rebounds_per_game', models.FloatField(default=0)),
                ('assists_per_game', models.FloatField(default=0)),
                ('steals_per_game', models.FloatField(default=0)),
                ('blocks_per_game', models.FloatField(default=0)),
                ('turnovers_per_game', models.FloatField(default=0)),
                ('field_goal_percentage', models.FloatField(default=0)),
                ('three_point_percentage', models.FloatField(default=0)),
                ('free_throw_percentage', models.FloatField(default=0)),
                ('player_efficiency_rating', models.FloatField(default=0)),
                ('usage_rate', models.FloatField(default=0)),
                ('true_shooting_percentage', models.FloatField(default=0)),
                ('offensive_rating', models.FloatField(default=0)),
                ('defensive_rating', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_injured', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=20)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offensive_rating', models.FloatField(blank=True, null=True)),
                ('defensive_rating', models.FloatField(blank=True, null=True)),
                ('net_rating', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='lineups', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='LineupComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points_diff', models.FloatField(blank=True, null=True)),
                ('rebounds_diff', models.FloatField(blank=True, null=True)),
                ('assists_diff', models.FloatField(blank=True, null=True)),
                ('net_rating_diff', models.FloatField(blank=True, null=True)),
                ('lineup1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_first', to='api.lineup')),
                ('lineup2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_second', to='api.lineup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team'),
        ),
    ]
